// SPDX-License-Identifier: AGPL-3.0-or-later
package cc.fluxus.racket;

// Generated by build.sh. The extraction marker is named after this, so a rebuilt
// runtime replaces the extracted one instead of being silently ignored — the
// same class of trap as a stale .zo shadowing an edited .ss.
public final class BuildId {
    public static final String ID = "@BUILD_ID@";
    private BuildId() {}
}
