// SPDX-License-Identifier: AGPL-3.0-or-later
#include "android_control.h"

#include <android/log.h>

#include <arpa/inet.h>
#include <netinet/in.h>
#include <poll.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <unistd.h>

#include <cerrno>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <string>
#include <thread>

#define LOG(...) __android_log_print(ANDROID_LOG_INFO, "fluxus", __VA_ARGS__)

namespace fluxctl {
namespace {

std::mutex  g_m;
std::string g_source;       // what is running (or about to)
std::string g_error;        // last eval error, "" = ok
bool        g_dirty = false;
std::string g_path;
time_t      g_mtime = 0;    // last mtime we have already taken

void setSource(const std::string& s) {
  std::lock_guard<std::mutex> lk(g_m);
  g_source = s;
  g_dirty  = true;
}

// --- the smallest JSON that talks to cli/fluxus -----------------------------
//
// Not a general parser: the requests are machine-generated by cli/main.go and
// mcp/main.go and are always a flat object of string values. It decodes the
// escapes those emit, which is what `code` needs — a sketch is full of newlines
// and quotes.

std::string jsonUnescape(const std::string& in) {
  std::string out;
  out.reserve(in.size());
  for (size_t i = 0; i < in.size(); ++i) {
    if (in[i] != '\\') { out += in[i]; continue; }
    if (++i >= in.size()) break;
    switch (in[i]) {
      case 'n': out += '\n'; break;
      case 'r': out += '\r'; break;
      case 't': out += '\t'; break;
      case 'b': out += '\b'; break;
      case 'f': out += '\f'; break;
      case 'u': {
        if (i + 4 >= in.size()) return out;
        const unsigned cp = (unsigned) strtoul(in.substr(i + 1, 4).c_str(), nullptr, 16);
        i += 4;
        if (cp < 0x80) {
          out += (char) cp;
        } else if (cp < 0x800) {
          out += (char) (0xC0 | (cp >> 6));
          out += (char) (0x80 | (cp & 0x3F));
        } else {
          // Surrogate pairs are left alone: Go escapes non-ASCII only when it
          // has to, and a lone half here would corrupt the sketch either way.
          out += (char) (0xE0 | (cp >> 12));
          out += (char) (0x80 | ((cp >> 6) & 0x3F));
          out += (char) (0x80 | (cp & 0x3F));
        }
        break;
      }
      default: out += in[i]; break;    // covers \" and \\ and \/
    }
  }
  return out;
}

// Value of a top-level string field, honouring backslash escapes so a `"` inside
// the sketch does not end the value early.
bool jsonString(const std::string& doc, const char* key, std::string& out) {
  const std::string pat = std::string("\"") + key + "\"";
  size_t k = doc.find(pat);
  if (k == std::string::npos) return false;
  k = doc.find(':', k + pat.size());
  if (k == std::string::npos) return false;
  while (k + 1 < doc.size() && (doc[k + 1] == ' ' || doc[k + 1] == '\t')) ++k;
  if (k + 1 >= doc.size() || doc[k + 1] != '"') return false;
  const size_t start = k + 2;
  size_t i = start;
  for (; i < doc.size(); ++i) {
    if (doc[i] == '\\') { ++i; continue; }
    if (doc[i] == '"') break;
  }
  if (i >= doc.size()) return false;
  out = jsonUnescape(doc.substr(start, i - start));
  return true;
}

std::string jsonEscape(const std::string& in) {
  std::string out;
  out.reserve(in.size() + 16);
  for (unsigned char c : in) {
    switch (c) {
      case '"':  out += "\\\""; break;
      case '\\': out += "\\\\"; break;
      case '\n': out += "\\n";  break;
      case '\r': out += "\\r";  break;
      case '\t': out += "\\t";  break;
      default:
        if (c < 0x20) { char b[8]; std::snprintf(b, sizeof b, "\\u%04x", c); out += b; }
        else          { out += (char) c; }
    }
  }
  return out;
}

// --- file -------------------------------------------------------------------

bool readFile(const std::string& path, std::string& out) {
  FILE* f = std::fopen(path.c_str(), "rb");
  if (!f) return false;
  out.clear();
  char buf[16 * 1024];
  size_t n;
  while ((n = std::fread(buf, 1, sizeof buf, f)) > 0) out.append(buf, n);
  std::fclose(f);
  return true;
}

bool writeFile(const std::string& path, const std::string& data) {
  FILE* f = std::fopen(path.c_str(), "wb");
  if (!f) return false;
  const bool ok = std::fwrite(data.data(), 1, data.size(), f) == data.size();
  std::fclose(f);
  return ok;
}

time_t mtimeOf(const std::string& path) {
  struct stat st;
  return ::stat(path.c_str(), &st) == 0 ? st.st_mtime : 0;
}

// --- serving ----------------------------------------------------------------

bool readLine(int fd, std::string& out) {
  out.clear();
  char ch;
  for (;;) {
    const ssize_t n = ::read(fd, &ch, 1);
    if (n <= 0) return !out.empty();
    if (ch == '\n') return true;
    if (ch != '\r') out += ch;
    if (out.size() > 8u * 1024 * 1024) return true;   // sanity cap
  }
}

void handle(int fd) {
  std::string line;
  if (!readLine(fd, line)) return;

  std::string cmd;
  jsonString(line, "cmd", cmd);
  std::string resp;

  if (cmd == "load" || cmd == "eval") {
    std::string code;
    if (!jsonString(line, "code", code)) jsonString(line, "source", code);
    setSource(code);
    // Persist, so a sketch sent over the wire is still there after a restart —
    // and remember the mtime we just made, or the watcher would read its own
    // write back as a change.
    if (!g_path.empty() && writeFile(g_path, code)) g_mtime = mtimeOf(g_path);
    // Give the GL thread a few frames to evaluate, then report what happened.
    // The desktop server does the same for the same reason.
    std::this_thread::sleep_for(std::chrono::milliseconds(250));
    std::string err;
    { std::lock_guard<std::mutex> lk(g_m); err = g_error; }
    resp = "{\"ok\":true,\"error\":\"" + jsonEscape(err) + "\"}\n";
  } else if (cmd == "get") {
    std::string src;
    { std::lock_guard<std::mutex> lk(g_m); src = g_source; }
    resp = "{\"ok\":true,\"code\":\"" + jsonEscape(src) + "\"}\n";
  } else if (cmd == "error") {
    std::string err;
    { std::lock_guard<std::mutex> lk(g_m); err = g_error; }
    resp = "{\"ok\":true,\"error\":\"" + jsonEscape(err) + "\"}\n";
  } else {
    resp = "{\"ok\":false,\"error\":\"unknown cmd (this build serves load/eval/get/error)\"}\n";
  }

  ::send(fd, resp.data(), resp.size(), MSG_NOSIGNAL);
}

void run(int port) {
  const int ls = ::socket(AF_INET, SOCK_STREAM, 0);
  if (ls < 0) {
    // Without android.permission.INTERNET the app is not in the `inet` group and
    // socket() fails with EACCES — the file path still works, so say so and stop.
    LOG("control: socket() failed (%s) — file loading still works", std::strerror(errno));
    return;
  }
  int one = 1;
  ::setsockopt(ls, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);

  sockaddr_in addr {};
  addr.sin_family      = AF_INET;
  addr.sin_port        = htons((uint16_t) port);
  addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);   // adb forward reaches this
  if (::bind(ls, (sockaddr*) &addr, sizeof addr) != 0 || ::listen(ls, 4) != 0) {
    LOG("control: cannot listen on 127.0.0.1:%d (%s)", port, std::strerror(errno));
    ::close(ls);
    return;
  }
  LOG("control: live-coding control on 127.0.0.1:%d "
      "(adb forward tcp:%d tcp:%d, then cli/fluxus load ...)", port, port, port);

  for (;;) {
    pollfd p { ls, POLLIN, 0 };
    const int r = ::poll(&p, 1, 250);          // the wait doubles as the file poll
    if (r > 0 && (p.revents & POLLIN)) {
      const int fd = ::accept(ls, nullptr, nullptr);
      if (fd >= 0) { handle(fd); ::close(fd); }
    }
    if (!g_path.empty()) {
      const time_t m = mtimeOf(g_path);
      if (m != 0 && m != g_mtime) {
        g_mtime = m;
        std::string src;
        if (readFile(g_path, src)) {
          LOG("control: %s changed — reloading", g_path.c_str());
          setSource(src);
        }
      }
    }
  }
}

}  // namespace

void start(int port, const std::string& sketchPath, const std::string& source) {
  g_path  = sketchPath;
  g_mtime = mtimeOf(sketchPath);
  setSource(source);
  std::thread(run, port).detach();
}

bool poll(std::string& out) {
  std::lock_guard<std::mutex> lk(g_m);
  if (!g_dirty) return false;
  out     = g_source;
  g_dirty = false;
  return true;
}

void setError(const std::string& err) {
  std::lock_guard<std::mutex> lk(g_m);
  g_error = err;
}

}  // namespace fluxctl
