; NTSC filter smoke test — spinning colour cubes through the CRT decode.
(ntsc #t)
(ntsc-noise 10)
(ntsc-saturation 22)
(ntsc-scanlines #t)
(clear)
(background (vector 0.02 0.02 0.05))
(scale (vector 1.4 1.4 1.4))
(rotate (vector (* (time) 20) (* (time) 30) 0))
(colour (vector 1 0.3 0.1))
(push) (translate (vector -1.2 0 0)) (build-cube) (pop)
(colour (vector 0.1 1 0.3))
(push) (translate (vector 1.2 0 0)) (build-cube) (pop)
(colour (vector 0.2 0.4 1))
(build-cube)
(screenshot "/tmp/ntsc-smoke.png")
